import os

##############################################
# Snakefile ? main entry point
##############################################

configfile: "config/config.yaml"

include: "rules/roh.smk"

CHROMS = config["chromosomes"]
PLOT_CHR = config["PLOT_CHR"]

##############################################
# Final outputs
##############################################
rule all:
    input:
        "results/froh/merged_froh.tsv",
        "results/plots/roh_manhattan_genomewide.png",
        f"results/plots/roh_{PLOT_CHR}.png"

